name: Upload Models to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: 'greenixproject/machine-learning'
        path: 'ml-repo'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      working-directory: ./ml-repo
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow google-cloud-storage

    - name: Create Service Account Key File
      run: echo "$SERVICE_ACCOUNT_KEY" > ./ml-repo/service-account-key.json
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.UPLOAD_GCS_SERVICE_ACCOUNT_KEY }}

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ml-repo/service-account-key.json" >> $GITHUB_ENV

    - name: Run the script
      working-directory: ./ml-repo
      run: python convert.py
