name: Upload to GCS

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ML repo
      uses: actions/checkout@v2

    - name: Checkout CC repo
      uses: actions/checkout@v2
      with:
        repository: greenixproject/cloud-computing
        ref: testing-wf  # Branch tempat Anda menyimpan script model_upload.js
        path: cc-repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd cc-repo
        npm ci
        npm install @google-cloud/storage

    - name: Write GCP Service Account Key and Set Environment Variable
      env:
        GCP_SA_KEY: ${{ secrets.UPLOAD_GCS }}
      run: |
        echo "$GCP_SA_KEY" > ./cc-repo/credentials/service-account-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=./cc-repo/credentials/service-account-key.json" >> $GITHUB_ENV

    - name: Upload files to GCS
      run: node ./cc-repo/model_upload.js
