name: Upload model to GCS
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ML repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install @google-cloud/storage
          npm install fs-extra

      - name: Upload files to GCS
        run: |
          node -e "
          const fs = require('fs-extra');
          const { Storage } = require('@google-cloud/storage');
          const storage = new Storage({ projectId: 'tester-auth-57054', credentials: JSON.parse('${{ secrets.ML_CREDENTIALS }}') });
          const bucketName = 'tester-dataset';
          const folderName = 'dataset';

          async function uploadToGCS(filePath) {
            const fileName = filePath.split('/').pop();
            const bucket = storage.bucket(bucketName);
            await bucket.upload(filePath, {
              destination: `${folderName}/${fileName}`,
            });
            console.log('File ' + fileName + ' berhasil diunggah ke GCS.');
          }

          const files = fs.readdirSync('.').filter((file) => file.endsWith('.h5'));
          for (const file of files) {
            uploadToGCS(file);
          }"
