name: Upload Model to GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ML Repo
      uses: actions/checkout@v2
      with:
        repository: 'greenixproject/machine-learning'
        path: ml-repo

    - name: Checkout CC Repo
      uses: actions/checkout@v2
      with:
        repository: 'greenixproject/cloud-computing'
        path: cc-repo

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd cc-repo
        npm install

    - name: Run the script
      run: |
        cd cc-repo
        node model_upload.js
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.UPLOAD_GCS }}
