name: Upload Model to GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ML Repo
      uses: actions/checkout@v2

    - name: Checkout CC Repo
      uses: actions/checkout@v2
      with:
        repository: greenixproject/cloud-computing
        ref: testing-wf
        path: cc-repo

    - name: Write GCP Service Account Key to File and Set Environment Variable
      env:
        UPLOAD_GCS: ${{ secrets.UPLOAD_GCS }}
      run: |
        echo "$UPLOAD_GCS" > ./gcp-sa-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-sa-key.json" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd cc-repo
        npm install

    - name: Run the script
      run: |
        cd cc-repo
        node model_upload.js
