name: Upload Models to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ML Repo
      uses: actions/checkout@v2
      with:
        repository: 'greenixproject/machine-learning'
        path: 'ml-repo'

    - name: Checkout CC Repo
      uses: actions/checkout@v2
      with:
        repository: 'greenixproject/cloud-computing'
        path: 'cc-repo'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        cd cc-repo
        npm install

    - name: Create Service Account Key File
      run: echo "$UPLOAD_GCS" > ./cc-repo/service-account-key.json
      env:
        UPLOAD_GCS: ${{ secrets.UPLOAD_GCS }}

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=./cc-repo/service-account-key.json" >> $GITHUB_ENV

    - name: Run the script
      working-directory: ./cc-repo
      run: node model_upload.js
