name: Upload to GCS

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ML repo
      uses: actions/checkout@v2

    - name: Checkout CC repo
      uses: actions/checkout@v2
      with:
        repository: greenixproject/cloud-computing
        ref: testing-wf  # Branch tempat Anda menyimpan script model_upload.js
        path: cc-repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd cc-repo
        npm ci
        npm install @google-cloud/storage

    - name: Set GCP Service Account Key as Environment Variable
      env:
        UPLOAD_GCS: ${{ secrets.UPLOAD_GCS }}  # Ganti GCP_SA_KEY dengan UPLOAD_GCS
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=$UPLOAD_GCS" >> $GITHUB_ENV

    - name: Upload files to GCS
      run: node ./cc-repo/model_upload.js
